### ISSUE TITLE
Suxerencia cambio nome 

### ISSUE THREAD

**Issue by AntonSono** [AlexSono/silabea#1]
cambiarlle o nome a  **silabetea**, acabo de buscar en github e tira moitos resultados para silabea igual asi reducimos . ou con **silabe-tea**
jejeje

A ver si a tarde podo editar algo de codigo dende aqui. diretamente

**Comment by AlexSono** [comment]
Ok , cambiamos nome

**Comment by AlexSono** [comment]
Listo agora  se chamara silabe-tea

**Comment by AlexSono** [comment]
Listo
